experiment_runner:
  #  plots:
  #    visualize_currents: True
  #    plot_3d:
  #      [ "error" ] #, "std_error", "initial_forecast", "water", "ground_truth" ]
  #    visualize_metrics: True
  metrics:
    - "rmse"
    - "r2"
    - "vme"
    - "ratio_per_tile"
    #- "vector_correlation"
  direction_current: [ "uv" ]# , "u", "v" ]

  #number_burnin_steps: 50
  number_burnin_steps: 0
  number_steps_prediction: 96
  delta_between_predictions_in_sec: 3600 #1h
  time_horizon_predictions_in_sec: 86400 # 24 *3600
  radius_area_around_platform: 1 #0.5
  number_steps_to_predict: 12
  gt_additional_area: 0.1
  gt_additional_time: 3600

  use_real_data: True
  scenario_used: "gm_GP_05_24"
  folder_scenario: "./ablation_study/configs_GP"

observer:
  life_span_observations_in_sec: 100000 # 12 * 3600

  model:

    gaussian_process:
      kernel:
        type: 'matern'
        sigma_exp_squared: 5.011571057964094
        scaling:
          latitude: 0.5753005356364821
          longitude: 0.5967749664273109
          time: 42103.57591355196
        parameters:
          #length_scale_bounds: "fixed"
          nu: 1.5
          length_scale_bounds: [ 0.00001, 1000000000000000000 ]

