---
arguments_model_runner:
  yaml_file_datasets: "config_neural_net"
  batch_size: 4096
  model_type: "rnn"
  log_interval: 1
  lr: 0.001
  folder_figure: "./figures/"
arguments_script_convert_data:
  yaml_file_datasets: "config_neural_net"
model:
  cfg_neural_network:
    input_shape: [ 2, 24, 24 ] # Not include the time dimension
    hidden_size: 1152 #2*24*24
    output_shape: [ 2, 24, 24 ] # Not include the time dimension
    type_cell: 'lstm'
    #size_layers_after_rnn: []
    num_layers: 2
    bidirectional: True
    dropout: 0
    init_weights_function: "randn"
  cfg_dataset:
    radius_lon: 1
    radius_lat: 1
    margin_forecast: 0
    stride_tiles_dataset: 0.1
    time_horizon_input_h: 12
    time_horizon_output_h: 12
    stride_time_dataset_h: 12
    input_shape:
      - 2
      - 12
      - 24
      - 24
    output_shape:
      - 2
      - 12
      - 24
      - 24
    index_axis_time: 2
    shift_window_input: 0
  model_error: true
data_generation:
  parameters_input:
    start_training: '2022-04-02T12:30:01Z'
    duration_training_in_h: 240 #672 # 28 * 24
    start_validation: '2022-05-04T12:30:01Z'
    duration_validation_in_h: 240 # 14 * 24
    input_tile_dims: [ 24, 24, 12 ]
    window_shift: 0 # if window shift = 2: input: [x{t-2} .. x{t+2}]
    # if window shift = 0: input= [x{t}...x{t+4}]
    output_tile_dims: [ 24, 24, 12 ]
    size_per_file_in_mb: 2000
    folder_training: "./data_NN/data_training_10_days_lstm/"
    folder_validation: "./data_NN/data_training_10_days_lstm/"
config_neural_net:
  training:
    hindcast:
      field: 'OceanCurrents'
      source: 'hindcast_files'
      source_settings:
        #'folder': "data/single_day_hindcasts/" #21/11/2021 -> 12/12/2021#"data/hindcast_test/"
        #'folder': 'data/single_day_hindcasts/' # 21/11 -> 27/11 + 22/12 -> 27/12
        #'folder': 'data/april_may_data/hindcast_HYCOM_all_one_file_april/'
        'folder': 'data/april_may_data/hindcast_hycom_april/'
      #'folder': 'data/hindcast_HYCOM_all_one_file_april/'
    forecast:
      field: 'OceanCurrents'
      source: 'forecast_files'
      source_settings:
        #'folder': "data/forecast_test/"# "data/cop_fmrc/" # 21/11/2021 -> 06/12/2021
        #'folder': "data/unique_forecast_test/" # 22/11/2021 -> 28/11/2021
        'folder': 'data/april_may_data/forecast_Copernicus_april_may/'
        #'folder': 'data/april_may_data/forecasts_HYCOM_april_8th_to_june_6th/'
        'currents': 'total'
  validation:
    hindcast:
      field: 'OceanCurrents'
      source: 'hindcast_files'
      source_settings:
        #'folder': "data/single_day_hindcasts/" #21/11/2021 -> 12/12/2021#"data/hindcast_test/"
        #'folder': 'data/single_day_hindcasts/' # 21/11 -> 27/11 + 22/12 -> 27/12
        #'folder': 'data/april_may_data/hindcast_HYCOM_all_one_file_april/'
        'folder': 'data/april_may_data/hindcast_hycom_may/'
      #'folder': 'data/hindcast_HYCOM_all_one_file_april/'
    forecast:
      field: 'OceanCurrents'
      source: 'forecast_files'
      source_settings:
        #'folder': "data/forecast_test/"# "data/cop_fmrc/" # 21/11/2021 -> 06/12/2021
        #'folder': "data/unique_forecast_test/" # 22/11/2021 -> 28/11/2021
        'folder': 'data/april_may_data/forecast_Copernicus_april_may/'
        #'folder': 'data/april_may_data/forecasts_HYCOM_april_8th_to_june_6th/'
        'currents': 'total'
